 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/aquatics", type: :request do
  
  # Aquatic. As you add validations to Aquatic, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Aquatic.create! valid_attributes
      get aquatics_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      aquatic = Aquatic.create! valid_attributes
      get aquatic_url(aquatic)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_aquatic_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      aquatic = Aquatic.create! valid_attributes
      get edit_aquatic_url(aquatic)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Aquatic" do
        expect {
          post aquatics_url, params: { aquatic: valid_attributes }
        }.to change(Aquatic, :count).by(1)
      end

      it "redirects to the created aquatic" do
        post aquatics_url, params: { aquatic: valid_attributes }
        expect(response).to redirect_to(aquatic_url(Aquatic.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Aquatic" do
        expect {
          post aquatics_url, params: { aquatic: invalid_attributes }
        }.to change(Aquatic, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post aquatics_url, params: { aquatic: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested aquatic" do
        aquatic = Aquatic.create! valid_attributes
        patch aquatic_url(aquatic), params: { aquatic: new_attributes }
        aquatic.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the aquatic" do
        aquatic = Aquatic.create! valid_attributes
        patch aquatic_url(aquatic), params: { aquatic: new_attributes }
        aquatic.reload
        expect(response).to redirect_to(aquatic_url(aquatic))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        aquatic = Aquatic.create! valid_attributes
        patch aquatic_url(aquatic), params: { aquatic: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested aquatic" do
      aquatic = Aquatic.create! valid_attributes
      expect {
        delete aquatic_url(aquatic)
      }.to change(Aquatic, :count).by(-1)
    end

    it "redirects to the aquatics list" do
      aquatic = Aquatic.create! valid_attributes
      delete aquatic_url(aquatic)
      expect(response).to redirect_to(aquatics_url)
    end
  end
end
